"""initial schema

Revision ID: 550ee73d7f07
Revises: 
Create Date: 2026-06-13 13:57:51.840397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550ee73d7f07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('my_retainers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('owner_character', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item_subcategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['item_category.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name')
    )
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('can_be_hq', sa.Boolean(), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subcategory_id'], ['item_subcategory.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('min_price_nq', sa.Integer(), nullable=True),
    sa.Column('min_price_hq', sa.Integer(), nullable=True),
    sa.Column('avg_price_nq', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_price_hq', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('listings_count_nq', sa.Integer(), nullable=True),
    sa.Column('listings_count_hq', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'collected_at')
    )
    op.create_table('my_active_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('retainer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_hq', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retainer_id'], ['my_retainers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retainer_id', 'item_id', 'is_hq')
    )
    op.create_table('sale_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sold_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('price_per_unit', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_hq', sa.Boolean(), nullable=False),
    sa.Column('buyer_name', sa.String(length=64), nullable=True),
    sa.Column('upload_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'sold_at', 'price_per_unit', 'quantity', 'is_hq', 'buyer_name')
    )
    op.create_table('my_inferred_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('retainer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('estimated_sold_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('price_per_unit', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_hq', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['my_active_listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retainer_id'], ['my_retainers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_inferred_sales')
    op.drop_table('sale_history')
    op.drop_table('my_active_listings')
    op.drop_table('market_snapshots')
    op.drop_table('items')
    op.drop_table('item_subcategory')
    op.drop_table('my_retainers')
    op.drop_table('item_category')
    # ### end Alembic commands ###
